package cn.com.chat.chat.chain.request.volcengine.imge;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * 火山引擎图片logo信息
 *
 * @author JiaZH
 * @date 2024-06-18
 */
@Data
@Builder
@NoArgsConstructor(force = true)
@AllArgsConstructor
public class VolcengineLogoInfo implements Serializable {

    /**
     * 是否添加水印
     */
    @JSONField(name = "add_logo")
    private Boolean addLogo;

    /**
     * 水印的位置，取值如下：
     * 0-右下角
     * 1-左下角
     * 2-左上角
     * 3-右上角
     * 默认0
     */
    private Integer position;

    /**
     * 水印的语言，取值如下：
     * 0-中文（AI生成）
     * 1-英文（Generated by AI）
     * 默认0
     */
    private Integer language;

    /**
     * 水印的不透明度，取值范围0-1，1表示完全不透明，默认0.3
     */
    private Double opacity;

}
